// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfmzieatmlvtunnppccp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmbXppZWF0bWx2dHVubnBwY2NwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDAyNjQsImV4cCI6MjA2MDkxNjI2NH0.eoVNABhBK2GflTsgs-CHi5CeXMTkAXgL96zEOEfZEDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);